/**
 * REQ-003 · AC-T-5 (D-24 / D-49): with `overrides.uuid = "11.1.1"` the Excel
 * export still works. A completed scan is written through
 * `ScanWorker.saveScanResults`, a `project_report` / `excel` report is
 * generated by the real `ReportService` into a temp folder, and the `.xlsx`
 * file is read back with ExcelJS: sheet names, header rows and data rows.
 * Real embedded PostgreSQL; OSV is a `fetch` stub (no network).
 */
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import ExcelJS from 'exceljs';
import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest';
import { ReportService } from '../../src/reports/reportService';
import { ScanWorker } from '../../src/scanner/worker';
import type { ScannedDependency } from '../../src/types/scan';
import { useTestDatabase } from '../helpers/db';

vi.setConfig({ testTimeout: 60_000, hookTimeout: 240_000 });

const db = useTestDatabase({ scope: 'file' });
let outDir = '';
let savedOut: string | undefined;

beforeEach(() => {
  outDir = fs.mkdtempSync(path.join(os.tmpdir(), 'ossr-xlsx-'));
  savedOut = process.env.REPORT_OUTPUT_DIR;
  process.env.REPORT_OUTPUT_DIR = outDir;
  vi.stubGlobal('fetch', vi.fn(async () => new Response(JSON.stringify({ vulns: [], results: [] }), { status: 200 })));
  vi.spyOn(console, 'log').mockImplementation(() => undefined);
  vi.spyOn(console, 'warn').mockImplementation(() => undefined);
});
afterEach(() => {
  vi.unstubAllGlobals();
  vi.restoreAllMocks();
  if (savedOut === undefined) delete process.env.REPORT_OUTPUT_DIR;
  else process.env.REPORT_OUTPUT_DIR = savedOut;
  fs.rmSync(outDir, { recursive: true, force: true });
});

function npm(name: string, version: string, licenses: string[]): ScannedDependency {
  return { ecosystem: 'nodejs', name, version, purl: `pkg:npm/${name}@${version}`, scope: 'direct', licenses, manifest_file: 'package.json', manifest_path: '.' };
}

/** Cell values of a row as strings (1-based columns, header row = 1). */
function rowValues(sheet: ExcelJS.Worksheet, row: number): string[] {
  const values = sheet.getRow(row).values as unknown[];
  return values.slice(1).map((v) => (v === null || v === undefined ? '' : String(v)));
}

describe('AC-T-5 / D-49: Excel export works with uuid 11.1.1', () => {
  it('AC-T-5: project_report.xlsx is generated (ready) and reads back with the expected sheets, headers and rows', async () => {
    const projectName = `qa-xlsx-${Math.random().toString(36).slice(2)}`;
    const [p] = await db.query<{ id: string }>(`INSERT INTO projects (name, repo_url) VALUES ($1, 'https://github.com/org/repo.git') RETURNING id`, [projectName]);
    const [s] = await db.query<{ id: string }>(`INSERT INTO scans (project_id, trigger, status, ref) VALUES ($1, 'manual', 'running', 'main') RETURNING id`, [p.id]);
    const deps = [npm('left-pad', '1.3.0', ['MIT']), npm('zz-gpl-lib', '2.0.0', ['GPL-3.0-only']), npm('mid-lib', '0.1.0', ['Apache-2.0'])];
    const worker = new ScanWorker({ db: db.pool, scanRoots: [], tmpRoot: outDir, logger: { log: () => undefined, warn: () => undefined, error: () => undefined } });
    await worker.saveScanResults(s.id, p.id, { scan_id: s.id, status: 'completed', total_deps: deps.length, dependencies: deps, scan_files: [], parse_errors: [] });

    const [u] = await db.query<{ id: string }>(`INSERT INTO users (email, display_name) VALUES ($1, 'QA') RETURNING id`, [`qa-${Math.random().toString(36).slice(2)}@example.test`]);
    const [r] = await db.query<{ id: string }>(
      `INSERT INTO reports (project_id, report_type, format, status, parameters, requested_by) VALUES ($1, 'project_report', 'excel', 'generating', $2::jsonb, $3) RETURNING id`,
      [p.id, JSON.stringify({ scanId: s.id }), u.id],
    );

    const record = await new ReportService(db.pool).processReport(r.id);
    expect(record.status).toBe('ready');
    expect(record.errorMessage).toBeNull();
    expect(record.storageKey).toBe(path.join(outDir, `report-${s.id}-project_report.xlsx`));
    const bytes = fs.readFileSync(record.storageKey!);
    expect(bytes.length).toBe(record.fileSizeBytes);
    expect(bytes.subarray(0, 2).toString('latin1')).toBe('PK'); // OOXML zip container

    const wb = new ExcelJS.Workbook();
    await wb.xlsx.readFile(record.storageKey!);
    expect(wb.worksheets.map((w) => w.name)).toEqual(['Summary', 'Dependencies', 'Licenses', 'Vulnerabilities']);

    const summary = wb.getWorksheet('Summary')!;
    expect(rowValues(summary, 1)).toEqual(['Metric', 'Value']);
    const metrics = new Map<string, string>();
    for (let i = 2; i <= summary.rowCount; i += 1) {
      const [k, v] = rowValues(summary, i);
      metrics.set(k, v);
    }
    expect(metrics.get('Project')).toBe(projectName);
    expect(metrics.get('Scan ID')).toBe(s.id);
    expect(metrics.get('Reference')).toBe('main');
    expect(metrics.get('Total Dependencies')).toBe('3');

    const depSheet = wb.getWorksheet('Dependencies')!;
    // REQ-004 D-63 / AC-P14-18: `License` and `License Source` appended; existing columns unchanged.
    expect(rowValues(depSheet, 1)).toEqual(['Name', 'Version', 'Ecosystem', 'Scope', 'Manifest', 'Depth', 'PURL', 'License', 'License Source']);
    expect(depSheet.rowCount).toBe(1 + deps.length);
    expect([2, 3, 4].map((i) => rowValues(depSheet, i)[0])).toEqual(['left-pad', 'mid-lib', 'zz-gpl-lib']); // ORDER BY name
    expect(rowValues(depSheet, 2)[6]).toBe('pkg:npm/left-pad@1.3.0');

    const licSheet = wb.getWorksheet('Licenses')!;
    expect(rowValues(licSheet, 1)).toEqual(['Package', 'Version', 'Detected License', 'Normalized License', 'Risk', 'Policy', 'Status', 'Suppressed']);
    const licRows = Array.from({ length: licSheet.rowCount - 1 }, (_, i) => rowValues(licSheet, i + 2));
    // One row per license finding: permitted licenses (MIT, Apache-2.0) raise no finding.
    expect(licRows.map((row) => row[0])).toEqual(['zz-gpl-lib']);
    expect(licRows[0][1]).toBe('2.0.0');
    expect(licRows[0][3]).toBe('GPL-3.0-only');

    const vulnSheet = wb.getWorksheet('Vulnerabilities')!;
    expect(rowValues(vulnSheet, 1)[0]).toBe('Package');
    expect(vulnSheet.rowCount).toBe(1); // no vulnerabilities (OSV stub)
  });
});
